city_positions = {
    "Rosebank": (0, 0),
    "Sandton": (4, 2),
    "Soweto": (-5, -5),
    "Melville": (2, -1),
    "Parktown": (3, 3),
    "Braamfontein": (5, 0),
    "Hillbrow": (6, -1),
    "Sandton High": (4, 3),
    "Soweto Primary": (-5, -6),
    "Rosebank College": (1, 1),
    "Parktown College": (3, 4),
    "Hillbrow Secondary": (6, -2),
    "Shell Rosebank": (0, 1),
    "Total Sandton": (5, 2),
    "Engen Soweto": (-6, -5),
    "BP Hillbrow": (6, -1.5),
    "M1@Empire": (2, -2),
    "N1@William Nicol": (5, 3),
    "M2@Ellis Park": (6, 0),
    "R24@Airport Rd": (10, -1),
    "M1@Sandton": (4, 1),
    "Zoo Lake": (-1, 0),
    "Emmarentia Park": (1, -1),
    "Delta Park": (3, 2),
    "Parktown Hospital": (3, 3.5),
    "Hillbrow Hospital": (6, -1.5),
    "Charlotte Maxeke": (5, 0.5),
    "Sandton City": (4, 2.5),
    "Braamfontein Office Park": (5, 0),
    "Park Station": (6, 1),
    "OR Tambo Airport": (10, -1)
}
